name: Ping Service

# Schedule: every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 min
  workflow_dispatch:  # optional manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: |
          URLS=(
            "https://sunmoonhaze.onrender.com"
            "https://google.com"
          )

          for url in "${URLS[@]}"; do
            echo "Pinging $url..."
            curl -Is --max-time 10 "$url" | head -n 1
            echo ""
          done
